---
- hosts: 192.168.1.130
  become: true

  tasks:
    - name: Update System
      apt:
        name: "*"
        state: latest
        update_cache: yes
        update_cache_retries: 2
        
    - name: Remove Unused Items
      apt:
        autoremove: yes
        autoclean: yes
        purge: yes
        
        
        
        
  
